### ISSUE TITLE
es6 import/export syntax highlight error

### ISSUE THREAD

**Issue by Tupbich** [madskristensen/VuePack#2] opened 2016-07-06 21:46 UTC
### Installed product versions
- Visual Studio:2015 Community
- This extension: 1.2.15
### Description

es6 import/export syntax highlight error
### Steps to recreate
1. Create new .vue file
2. Create script block
3. Type import foo from './foo';
### Screenshot

![image](https://cloud.githubusercontent.com/assets/11892513/16635691/25bb2ae2-43dc-11e6-97aa-626c9ea45bda.png)

**Comment by cybertino** [comment] 2016-07-07 23:17
@madskristensen Try `<script type="text/babel">`. Not sure whether it helps as I cannot manage VuePack to work in my Visual Studio.

**Comment by tiansh** [comment] 2016-08-02 09:58
It seems that this plugin just tell VS `.vue` is yet another extension for HTML files. So VS just parse this file using parser for HTML. But `<script>`s inlined in an HTML file is NOT allowed to write `export` (since you cannot do `import xxx.html` in another file). That's why VS complain these code as invalid.

**Comment by detaybey** [comment] 2016-08-24 14:21
any fix for this? without the import expression, this extension becomes useless as no vue application is with a single .vue file.

**Comment by madskristensen** [comment] 2016-08-24 15:11
The only thing you can do is to disable javascript validation in Tools -> Options. This extension cannot fix it, since there are no APIs to control the behavior.

**Comment by pimboden** [comment] 2016-10-10 08:31
Hello.
I installed the package, but It seems that its not working at all. No highlighting, no intellisence, nothing at all.
What am I doing wrong. I have VS2015 with update 3
I also don't know where to disable javascript validation... cant't fin it in tools/options

**Comment by cuibty** [comment] 2016-11-22 14:36
+1

**Comment by cucr** [comment] 2016-12-05 04:30
i have same problem,how to support ES6 features in .vue file?

**Comment by zeeglenn** [comment] 2016-12-13 00:57
same, no highlighting for vue files. the icon did change...

**Comment by Eshva** [comment] 2016-12-28 20:40
+1

**Comment by Eshva** [comment] 2016-12-28 21:22
May be this can help?
[https://msdn.microsoft.com/en-us/library/bb165071.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-3](url)

**Comment by Eshva** [comment] 2016-12-28 21:42
Here some workarounds. It's about JSX but could be useful. For me works Solution 1.
[http://stackoverflow.com/a/34110461/156991](url)

**Comment by csicky** [comment] 2017-02-25 16:51
Visual Studio WAS always the best IDE. Now I use VS Code but still miss VS's power. It looks like not even with extensions VS can't be fixed to bring it's (now lost) great development experience. What I read about VS 2017 seems to be the same. I was really hoping VS 2017 would allow me to come back from VS Code.
WebStorm and many others are leaving VS behind and Microsoft doesn't seem to notice or even care. By the time Microsoft brings support to some js library people already use a newer one. The only hope left is in VS Code, but that too needs extensions to get to an acceptable level.

@madskristensen - I really appreciate you great work over the years. You managed to keep VS as usable as you could for modern web development. The problem is that the framework is not allowing you to actually succeed in this.

I arrived to this issue page searching for "visual studio vue.js".

**Comment by madskristensen** [comment] 2017-03-01 17:59
This cannot be fixed in VS2015, but I just released a version of this extension for VS2017 which supports the import/export statements https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VuejsPack-18329

**Closed as completed by madskristensen** 2017-03-01 17:59 UTC

**Comment by mrns** [comment] 2017-08-08 02:14
Hi @madskristensen, thanks for your work! Just wanted to let you know that I have installed the v1.1.8 and still get this javascript ES6 Syntax Error. Should I install any other extension besides VuePack 2017?

![image](https://user-images.githubusercontent.com/847602/29053355-0124cfc6-7bc6-11e7-9781-4ba7c9907da2.png)

**Comment by ceferrari** [comment] 2017-11-01 00:25
@mrns same issue here

**Comment by fritz-net** [comment] 2018-08-11 21:36
I really like the extension, however I have the same problem:
![image](https://user-images.githubusercontent.com/2499282/43996264-31137af4-9dbf-11e8-95c7-d840dcec021b.png)

`<script type="text/babel>` totally disables syntax checking & highlighting
